---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Learn what's new in Kubernetes in Cloud Manager.
---

= What's new with Kubernetes in Cloud Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Kubernetes in Cloud Manager.

//tag::whats-new[]

== 6 June 2022

Cloud Manager now suports Amazon FSx for ONTAP as backend storage.  

== 4 May 2022

=== Drag and drop to add storage class
You can now drag your Kubernetes cluster and drop it onto the Cloud Volumes ONTAP working environment to add a storage class directly from the Canvas.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes[Add storage class]

== 4 April 2022

=== Manage Kubernetes clusters using the Cloud Manager resource page

Kubernetes cluster management now has enhanced integration directly from the cluster working environment. A new link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-quick-start.html[Quick start] gets you up and running quickly.

You can now take the following actions from the cluster resource page.

* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-trident.html[Install Astra Trident]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html[Add storage classes]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-persistent-volumes.html[View persistent volumes]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-remove-cluster.html[Remove clusters]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-kubernetes-enable-services.html[Enable data services]

//end::whats-new[]
== 27 February 2022

=== Support for Kubernetes clusters in Google Cloud

You can now add and manage managed Google Kubernetes Engine (GKE) clusters and self-managed Kubernetes clusters in Google Cloud using Cloud Manager.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-gke.html[Learn how to get started with Kubernetes clusters in Google Cloud].


//end::whats-new[]
== 11 January 2022

=== Support for Kubernetes clusters in Azure

You can now add and manage managed Azure Kubernetes clusters (AKS) and self-managed Kubernetes clusters in Azure using Cloud Manager.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-aks.html[Getting started with Kubernetes clusters in Azure]

== 28 November 2021

=== Support for Kubernetes clusters in AWS

You can now add your managed-Kubernetes clusters to Cloud Manager's Canvas for advanced data management.

* Discover Amazon EKS clusters
* Back up persistent volumes using Cloud Backup

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html[Learn more about Kubernetes support].

TIP: The existing Kubernetes service (available through the *K8s* tab) has been deprecated and will be removed in a future release.
